Added implementation for Tizen.NET
jamesmontemagno/TextToSpeechPlugin pull request #42
Opened 2017-12-05 06:53 UTC by JongHeonChoi

2017-12-05 16:11 UTC, jamesmontemagno requested changes

2017-12-05 16:11 UTC, jamesmontemagno commented on src/TextToSpeech.Plugin.Tizen/TextToSpeech.cs
> +			Task.Delay(1000);
Any specific reason for this here? I usually have an "Init();" Type method that I call before speaking back.

2017-12-05 16:11 UTC, jamesmontemagno commented on src/TextToSpeech.Plugin.Tizen/TextToSpeech.cs
> +			list = (List<SupportedVoice>)ttsInst.GetSupportedVoices();
Could this ever throw null? Maybe us " as List<SupportedVoice>

2017-12-05 16:11 UTC, jamesmontemagno commented on src/TextToSpeech.Plugin.Tizen/TextToSpeech.cs
> +			return Task.FromResult(list.Select(a => new CrossLocale { Language = a.Language }));
Does seem like list could be null here?

2018-02-06 04:55 UTC, JongHeonChoi commented
@jamesmontemagno @prashantvc Please, checking the code review.

2023-04-03 20:36 UTC, closed without merging